// TODO: needed by useState, move to another file
"use client"
import { useState } from 'react'

import { CeramicContextProvider } from '@/context/ceramic.context'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Sidebar } from "@/components/sidebar.component"
import { Profile } from '@/types'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Home',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [profile, setProfile] = useState<Profile | undefined>()

  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <CeramicContextProvider>
        {/* <Sidebar name = {profile?.name} username = {profile?.username} id={profile?.id}/> */}
        {children}
        </CeramicContextProvider>
        </body>
    </html>
  )
}
