// TODO: needed by useState, move to another file
"use client"
import { useState } from 'react'

import { CeramicContextProvider } from '@/context/ceramic.context'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Profile } from '@/types'

import { WagmiConfig, createConfig, mainnet } from 'wagmi'
import { createPublicClient, http } from 'viem'
import ThemeProvider from '@/providers/ThemeProvider'

const config = createConfig({
  autoConnect: true,
  publicClient: createPublicClient({
    chain: mainnet,
    transport: http()
  }),
})

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Home',
//   description: 'Generated by create next app',
// }

// export const metadata: Metadata = {
//   title: 'Horizon UI by Ories',
//   description: 'Generated by create next app',
//   applicationName: 'Horizon UI',
//   keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
//   themeColor: '#422AFB',
//   icons: [
//     // { rel: "icon", type: 'image/svg', url: "/map/location.svg" },
//     { rel: "apple-touch-icon", type: 'image/png', url: "/img/horizon.png" }
//   ],
//   generator: 'ichsankurnia',
//   authors: [{ name: 'ichsankurnia', url: 'https://ories.goes2nobel.com' }],
//   creator: 'ichsankurnia'
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [profile, setProfile] = useState<Profile | undefined>()

  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
      <ThemeProvider>
        <WagmiConfig config={config}>
           <CeramicContextProvider>
                {/* <Sidebar name = {profile?.name} username = {profile?.username} id={profile?.id}/> */}
                {children}
          </CeramicContextProvider>
       </WagmiConfig>
       </ThemeProvider>
      </body>
    </html>
  )
}
